define([], function () {

  // 1000 top terms
  return  [
    { value: "PhRvL", label: "Physical Review Letters (PhRvL)" },
    { value: "ApJ", label: "The Astrophysical Journal (ApJ)" },
    { value: "PhRvB", label: "Physical Review B (PhRvB)" },
    { value: "JChPh", label: "Journal of Chemical Physics (JChPh)" },
    { value: "Natur", label: "Nature (Natur)" },
    { value: "PhRvD", label: "Physical Review D (PhRvD)" },
    { value: "ApPhL", label: "Applied Physics Letters (ApPhL)" },
    { value: "Sci", label: "Science (Sci)" },
    { value: "JGR", label: "Journal of Geophysical Research (JGR)" },
    { value: "A&A", label: "Astronomy and Astrophysics (A&A)" },
    { value: "JAP", label: "Journal of Applied Physics (JAP)" },
    { value: "PhRv", label: "Physical Review (PhRv)" },
    { value: "MNRAS", label: "Monthly Notices of the Royal Astronomical Society (MNRAS)" },
    { value: "PhRvA", label: "Physical Review A (PhRvA)" },
    { value: "PhLB", label: "Physics Letters B (PhLB)" },
    { value: "NuPhB", label: "Nuclear Physics B (NuPhB)" },
    { value: "PNAS", label: "Proceedings of the National Academy of Science (PNAS)" },
    { value: "arXiv", label: "ArXiv e-prints (arXiv)" },
    { value: "GeoRL", label: "Geophysical Research Letters (GeoRL)" },
    { value: "PhRvE", label: "Physical Review E (PhRvE)" },
    { value: "PhRvC", label: "Physical Review C (PhRvC)" },
    { value: "JHEP", label: "Journal of High Energy Physics (JHEP)" },
    { value: "AJ", label: "The Astronomical Journal (AJ)" },
    { value: "CPL", label: "Chemical Physics Letters (CPL)" },
    { value: "NuPhA", label: "Nuclear Physics A (NuPhA)" },
    { value: "RvMP", label: "Reviews of Modern Physics (RvMP)" },
    { value: "OptL", label: "Optics Letters (OptL)" },
    { value: "E&PSL", label: "Earth and Planetary Science Letters (E&PSL)" },
    { value: "GeCoA", label: "Geochimica et Cosmochimica Acta (GeCoA)" },
    { value: "SurSc", label: "Surface Science (SurSc)" },
    { value: "ApOpt", label: "Applied Optics (ApOpt)" },
    { value: "SPIE", label: "Society of Photo-Optical Instrumentation Engineers (SPIE) Conference Series (SPIE)" },
    { value: "JFM", label: "Journal of Fluid Mechanics (JFM)" },
    { value: "ApJS", label: "The Astrophysical Journal Supplement Series (ApJS)" },
    { value: "OExpr", label: "Optics Express (OExpr)" },
    { value: "PhLA", label: "Physics Letters A (PhLA)" },
    { value: "JaJAP", label: "Japanese Journal of Applied Physics (JaJAP)" },
    { value: "JPSJ", label: "Journal of the Physical Society of Japan (JPSJ)" },
    { value: "SSCom", label: "Solid State Communications (SSCom)" },
    { value: "RSPSA", label: "Proceedings of the Royal Society of London Series A (RSPSA)" },
    { value: "JAtS", label: "Journal of Atmospheric Sciences (JAtS)" },
    { value: "JPCM", label: "Journal of Physics Condensed Matter (JPCM)" },
    { value: "JPhA", label: "Journal of Physics A Mathematical General (JPhA)" },
    { value: "PLoSO", label: "PLoS ONE (PLoSO)" },
    { value: "PhR", label: "Physics Reports (PhR)" },
    { value: "JPhB", label: "Journal of Physics B Atomic Molecular Physics (JPhB)" },
    { value: "RScI", label: "Review of Scientific Instruments (RScI)" },
    { value: "PhFl", label: "Physics of Fluids (PhFl)" },
    { value: "EnST", label: "Environmental Science and Technology (EnST)" },
    { value: "JGRD", label: "Journal of Geophysical Research (Atmospheres) (JGRD)" },
    { value: "MaMol", label: "Macromolecules (MaMol)" },
    { value: "NanoL", label: "Nano Letters (NanoL)" },
    { value: "JCli", label: "Journal of Climate (JCli)" },
    { value: "NIMPA", label: "Nuclear Instruments and Methods in Physics Research A (NIMPA)" },
    { value: "AtmEn", label: "Atmospheric Environment (AtmEn)" },
    { value: "ASAJ", label: "Acoustical Society of America Journal (ASAJ)" },
    { value: "WRR", label: "Water Resources Research (WRR)" },
    { value: "Icar", label: "Icarus (Icar)" },
    { value: "JCrGr", label: "Journal of Crystal Growth (JCrGr)" },
    { value: "JMP", label: "Journal of Mathematical Physics (JMP)" },
    { value: "TSF", label: "Thin Solid Films (TSF)" },
    { value: "Geo", label: "Geology (Geo)" },
    { value: "PhPl", label: "Physics of Plasmas (PhPl)" },
    { value: "JMMM", label: "Journal of Magnetism and Magnetic Materials (JMMM)" },
    { value: "OptCo", label: "Optics Communications (OptCo)" },
    { value: "EL", label: "EPL (Europhysics Letters) (EL)" },
    { value: "MWRv", label: "Monthly Weather Review (MWRv)" },
    { value: "JCoPh", label: "Journal of Computational Physics (JCoPh)" },
    { value: "AnPhy", label: "Annals of Physics (AnPhy)" },
    { value: "Tectp", label: "Tectonophysics (Tectp)" },
    { value: "JPhD", label: "Journal of Physics D Applied Physics (JPhD)" },
    { value: "NIMPB", label: "Nuclear Instruments and Methods in Physics Research B (NIMPB)" },
    { value: "ITM", label: "IEEE Transactions on Magnetics (ITM)" },
    { value: "CMaPh", label: "Communications in Mathematical Physics (CMaPh)" },
    { value: "JPhC", label: "Journal of Physics C Solid State Physics (JPhC)" },
    { value: "PSSBR", label: "Physica Status Solidi B Basic Research (PSSBR)" },
    { value: "JNCS", label: "Journal of Non Crystalline Solids (JNCS)" },
    { value: "CQGra", label: "Classical and Quantum Gravity (CQGra)" },
    { value: "SoPh", label: "Solar Physics (SoPh)" },
    { value: "ACP", label: "Atmospheric Chemistry & Physics (ACP)" },
    { value: "IJQE", label: "IEEE Journal of Quantum Electronics (IJQE)" },
    { value: "PhDT", label: "Ph.D. Thesis (PhDT)" },
    { value: "MolPh", label: "Molecular Physics (MolPh)" },
    { value: "NatMa", label: "Nature Materials (NatMa)" },
    { value: "ApSS", label: "Applied Surface Science (ApSS)" },
    { value: "PASP", label: "Publications of the Astronomical Society of the Pacific (PASP)" },
    { value: "AIPC", label: "American Institute of Physics Conference Series (AIPC)" },
    { value: "PhyC", label: "Physica C Superconductivity (PhyC)" },
    { value: "PThPh", label: "Progress of Theoretical Physics (PThPh)" },
    { value: "BpJ", label: "Biophysical Journal (BpJ)" },
    { value: "JNuM", label: "Journal of Nuclear Materials (JNuM)" },
    { value: "ITED", label: "IEEE Transactions on Electron Devices (ITED)" },
    { value: "PhyA", label: "Physica A Statistical Mechanics and its Applications (PhyA)" },
    { value: "JPCS", label: "Journal of Physics and Chemistry of Solids (JPCS)" },
    { value: "ITGRS", label: "IEEE Transactions on Geoscience and Remote Sensing (ITGRS)" },
    { value: "CoMP", label: "Contributions to Mineralogy and Petrology (CoMP)" },
    { value: "JHyd", label: "Journal of Hydrology (JHyd)" },
    { value: "ZPhy", label: "Zeitschrift fur Physik (ZPhy)" },
    { value: "CP", label: "Chemical Physics (CP)" },
    { value: "A&AS", label: "Astronomy and Astrophysics Supplement Series (A&AS)" },
    { value: "JCAP", label: "Journal of Cosmology and Astro-Particle Physics (JCAP)" },
    { value: "ARA&A", label: "Annual Review of Astronomy and Astrophysics (ARA&A)" },
    { value: "QJRMS", label: "Quarterly Journal of the Royal Meteorological Society (QJRMS)" },
    { value: "GeoJI", label: "Geophysical Journal International (GeoJI)" },
    { value: "EPJC", label: "European Physical Journal C (EPJC)" },
    { value: "JOSAB", label: "Journal of the Optical Society of America B Optical Physics (JOSAB)" },
    { value: "JVST", label: "Journal of Vacuum Science Technology (JVST)" },
    { value: "JMoSp", label: "Journal of Molecular Spectroscopy (JMoSp)" },
    { value: "JPO", label: "Journal of Physical Oceanography (JPO)" },
    { value: "ITAP", label: "IEEE Transactions on Antennas and Propagation (ITAP)" },
    { value: "NatSR", label: "Scientific Reports (NatSR)" },
    { value: "JGRA", label: "Journal of Geophysical Research (Space Physics) (JGRA)" },
    { value: "RSEnv", label: "Remote Sensing of Environment (RSEnv)" },
    { value: "PhyB", label: "Physica B Condensed Matter (PhyB)" },
    { value: "ITNS", label: "IEEE Transactions on Nuclear Science (ITNS)" },
    { value: "JPCA", label: "Journal of Physical Chemistry A (JPCA)" },
    { value: "IPTL", label: "IEEE Photonics Technology Letters (IPTL)" },
    { value: "NJPh", label: "New Journal of Physics (NJPh)" },
    { value: "PSSAR", label: "Physica Status Solidi Applied Research (PSSAR)" },
    { value: "NatCo", label: "Nature Communications (NatCo)" },
    { value: "JMatS", label: "Journal of Materials Science (JMatS)" },
    { value: "CoPhC", label: "Computer Physics Communications (CoPhC)" },
    { value: "GSAB", label: "Geological Society of America Bulletin (GSAB)" },
    { value: "RPPh", label: "Reports on Progress in Physics (RPPh)" },
    { value: "JLwT", label: "Journal of Lightwave Technology (JLwT)" },
    { value: "NatPh", label: "Nature Physics (NatPh)" },
    { value: "RSPTA", label: "Philosophical Transactions of the Royal Society of London Series A (RSPTA)" },
    { value: "PCCP", label: "Physical Chemistry Chemical Physics (Incorporating Faraday Transactions) (PCCP)" },
    { value: "P&SS", label: "Planetary and Space Science (P&SS)" },
    { value: "Geop", label: "Geophysics (Geop)" },
    { value: "ITMTT", label: "IEEE Transactions on Microwave Theory Techniques (ITMTT)" },
    { value: "ChGeo", label: "Chemical Geology (ChGeo)" },
    { value: "JPS", label: "Journal of Power Sources (JPS)" },
    { value: "APS", label: "APS Meeting Abstracts (APS)" },
    { value: "ASPC", label: "Astronomical Society of the Pacific Conference Series (ASPC)" },
    { value: "JOSAA", label: "Journal of the Optical Society of America A (JOSAA)" },
    { value: "CaJPh", label: "Canadian Journal of Physics (CaJPh)" },
    { value: "JSV", label: "Journal of Sound Vibration (JSV)" },
    { value: "JGRB", label: "Journal of Geophysical Research (Solid Earth) (JGRB)" },
    { value: "Nanot", label: "Nanotechnology (Nanot)" },
    { value: "PhyD", label: "Physica D Nonlinear Phenomena (PhyD)" },
    { value: "AGUFM", label: "AGU Fall Meeting Abstracts (AGUFM)" },
    { value: "SSRv", label: "Space Science Reviews (SSRv)" },
    { value: "AIAAJ", label: "AIAA Journal (AIAAJ)" },
    { value: "JOSA", label: "Journal of the Optical Society of America (1917-1983) (JOSA)" },
    { value: "JETP", label: "Soviet Journal of Experimental and Theoretical Physics (JETP)" },
    { value: "JSSCh", label: "Journal of Solid State Chemistry France (JSSCh)" },
    { value: "QSRv", label: "Quaternary Science Reviews (QSRv)" },
    { value: "PMag", label: "Philosophical Magazine (PMag)" },
    { value: "JETPL", label: "Soviet Journal of Experimental and Theoretical Physics Letters (JETPL)" },
    { value: "JSP", label: "Journal of Statistical Physics (JSP)" },
    { value: "MedPh", label: "Medical Physics (MedPh)" },
    { value: "NucIM", label: "Nuclear Instruments and Methods (NucIM)" },
    { value: "Ap&SS", label: "Astrophysics and Space Science (Ap&SS)" },
    { value: "IAUS", label: "IAU Symposium (IAUS)" },
    { value: "JQSRT", label: "Journal of Quantitative Spectroscopy and Radiative Transfer (JQSRT)" },
    { value: "SSEle", label: "Solid State Electronics (SSEle)" },
    { value: "IEDL", label: "IEEE Electron Device Letters (IEDL)" },
    { value: "ApPhA", label: "Applied Physics A: Materials Science & Processing (ApPhA)" },
    { value: "NucFu", label: "Nuclear Fusion (NucFu)" },
    { value: "NaPho", label: "Nature Photonics (NaPho)" },
    { value: "JVGR", label: "Journal of Volcanology and Geothermal Research (JVGR)" },
    { value: "JApMe", label: "Journal of Applied Meteorology (JApMe)" },
    { value: "JPhG", label: "Journal of Physics G Nuclear Physics (JPhG)" },
    { value: "PEPI", label: "Physics of the Earth and Planetary Interiors (PEPI)" },
    { value: "AdSpR", label: "Advances in Space Research (AdSpR)" },
    { value: "IJRS", label: "International Journal of Remote Sensing (IJRS)" },
    { value: "ApPhB", label: "Applied Physics B: Lasers and Optics (ApPhB)" },
    { value: "JMoSt", label: "Journal of Molecular Structure (JMoSt)" },
    { value: "BAMS", label: "Bulletin of the American Meteorological Society (BAMS)" },
    { value: "JMagR", label: "Journal of Magnetic Resonance (JMagR)" },
    { value: "NucPh", label: "Nuclear Physics (NucPh)" },
    { value: "AdPhy", label: "Advances in Physics (AdPhy)" },
    { value: "AcSpA", label: "Spectrochimica Acta Part A: Molecular Spectroscopy (AcSpA)" },
    { value: "ClDy", label: "Climate Dynamics (ClDy)" },
    { value: "NatNa", label: "Nature Nanotechnology (NatNa)" },
    { value: "PASJ", label: "Publications of the Astronomical Society of Japan (PASJ)" },
    { value: "JGRC", label: "Journal of Geophysical Research (Oceans) (JGRC)" },
    { value: "AmJPh", label: "American Journal of Physics (AmJPh)" },
    { value: "IJMPA", label: "International Journal of Modern Physics A (IJMPA)" },
    { value: "Phy", label: "Physica (Phy)" },
    { value: "CMAME", label: "Computer Methods in Applied Mechanics and Engineering (CMAME)" },
    { value: "JSG", label: "Journal of Structural Geology (JSG)" },
    { value: "JMatR", label: "Journal of Materials Research (JMatR)" },
    { value: "NYASA", label: "Annals of the New York Academy of Sciences (NYASA)" },
    { value: "PMB", label: "Physics in Medicine and Biology (PMB)" },
    { value: "Litho", label: "Lithos (Litho)" },
    { value: "GBioC", label: "Global Biogeochemical Cycles (GBioC)" },
    { value: "PhyS", label: "Physica Scripta (PhyS)" },
    { value: "AnP", label: "Annalen der Physik (AnP)" },
    { value: "ITSP", label: "IEEE Transactions on Signal Processing (ITSP)" },
    { value: "PPCF", label: "Plasma Physics and Controlled Fusion (PPCF)" },
    { value: "JPet", label: "Journal of Petrology (JPet)" },
    { value: "GeoJ", label: "Geophysical Journal (GeoJ)" },
    { value: "JPhCS", label: "Journal of Physics Conference Series (JPhCS)" },
    { value: "ZPhyB", label: "Zeitschrift fur Physik B Condensed Matter (ZPhyB)" },
    { value: "MPLA", label: "Modern Physics Letters A (MPLA)" },
    { value: "HyPr", label: "Hydrological Processes (HyPr)" },
    { value: "JLTP", label: "Journal of Low Temperature Physics (JLTP)" },
    { value: "JVSTB", label: "Journal of Vacuum Science Technology B: Microelectronics and Nanometer Structures (JVSTB)" },
    { value: "Tecto", label: "Tectonics (Tecto)" },
    { value: "JG", label: "Journal of Geology (JG)" },
    { value: "PreR", label: "Precambrian Research (PreR)" },
    { value: "EPJB", label: "European Physical Journal B (EPJB)" },
    { value: "NuPhS", label: "Nuclear Physics B Proceedings Supplements (NuPhS)" },
    { value: "ZNatA", label: "Zeitschrift Naturforschung Teil A (ZNatA)" },
    { value: "AcSpe", label: "Spectrochimica Acta (AcSpe)" },
    { value: "ITPS", label: "IEEE Transactions on Plasma Science (ITPS)" },
    { value: "LNP", label: "Lecture Notes in Physics, Berlin Springer Verlag (LNP)" },
    { value: "DSRII", label: "Deep Sea Research Part II: Topical Studies in Oceanography (DSRII)" },
    { value: "JATP", label: "Journal of Atmospheric and Terrestrial Physics (JATP)" },
    { value: "Geomo", label: "Geomorphology (Geomo)" },
    { value: "PalOc", label: "Paleoceanography (PalOc)" },
    { value: "math", label: "ArXiv Mathematics e-prints (math)" },
    { value: "JPhF", label: "Journal of Physics F Metal Physics (JPhF)" },
    { value: "BoLMe", label: "Boundary-Layer Meteorology (BoLMe)" },
    { value: "ZPhyC", label: "Zeitschrift fur Physik C Particles and Fields (ZPhyC)" },
    { value: "SuScT", label: "Superconductor Science Technology (SuScT)" },
    { value: "RaSc", label: "Radio Science (RaSc)" },
    { value: "PhL", label: "Physics Letters (PhL)" },
    { value: "JCIS", label: "Journal of Colloid and Interface Science (JCIS)" },
    { value: "OptEn", label: "Optical Engineering (OptEn)" },
    { value: "JPoSA", label: "Journal of Polymer Science A Polymer Chemistry (JPoSA)" },
    { value: "IJNME", label: "International Journal for Numerical Methods in Engineering (IJNME)" },
    { value: "AnGeo", label: "Annales Geophysicae (AnGeo)" },
    { value: "ApSpe", label: "Applied Spectroscopy (ApSpe)" },
    { value: "NatGe", label: "Nature Geoscience (NatGe)" },
    { value: "SMat", label: "Soft Matter (SMat)" },
    { value: "AnRFM", label: "Annual Review of Fluid Mechanics (AnRFM)" },
    { value: "SeScT", label: "Semiconductor Science Technology (SeScT)" },
    { value: "PPS", label: "Proceedings of the Physical Society (PPS)" },
    { value: "ZPhyA", label: "Zeitschrift fur Physik A Hadrons and Nuclei (ZPhyA)" },
    { value: "GReGr", label: "General Relativity and Gravitation (GReGr)" },
    { value: "JMPSo", label: "Journal of Mechanics Physics of Solids (JMPSo)" },
    { value: "RvGeo", label: "Reviews of Geophysics (RvGeo)" },
    { value: "ADNDT", label: "Atomic Data and Nuclear Data Tables (ADNDT)" },
    { value: "LimOc", label: "Limnology and Oceanography (LimOc)" },
    { value: "JLum", label: "Journal of Luminescence (JLum)" },
    { value: "ARPC", label: "Annual Review of Physical Chemistry (ARPC)" },
    { value: "GGG", label: "Geochemistry, Geophysics, Geosystems (GGG)" },
    { value: "IJCli", label: "International Journal of Climatology (IJCli)" },
    { value: "JAtOT", label: "Journal of Atmospheric and Oceanic Technology (JAtOT)" },
    { value: "JEMat", label: "Journal of Electronic Materials (JEMat)" },
    { value: "JGlac", label: "Journal of Glaciology (JGlac)" },
    { value: "DRM", label: "Diamond and Related Materials (DRM)" },
    { value: "CaJES", label: "Canadian Journal of Earth Sciences (CaJES)" },
    { value: "ECSS", label: "Estuarine Coastal and Shelf Science (ECSS)" },
    { value: "CSR", label: "Continental Shelf Research (CSR)" },
    { value: "Ana", label: "The Analyst (Ana)" },
    { value: "ChPhL", label: "Chinese Physics Letters (ChPhL)" },
    { value: "QuRes", label: "Quaternary Research (QuRes)" },
    { value: "NCimA", label: "Nuovo Cimento A Serie (NCimA)" },
    { value: "AN", label: "Astronomische Nachrichten (AN)" },
    { value: "ITIP", label: "IEEE Transactions on Image Processing (ITIP)" },
    { value: "QuEle", label: "Quantum Electronics (QuEle)" },
    { value: "Nanos", label: "Nanoscale (Nanos)" },
    { value: "AREPS", label: "Annual Review of Earth and Planetary Sciences (AREPS)" },
    { value: "NW", label: "Naturwissenschaften (NW)" },
    { value: "MeScT", label: "Measurement Science and Technology (MeScT)" },
    { value: "Sedim", label: "Sedimentology (Sedim)" },
    { value: "CSF", label: "Chaos Solitons and Fractals (CSF)" },
    { value: "LPI", label: "Lunar and Planetary Science Conference (LPI)" },
    { value: "EPJA", label: "European Physical Journal A (EPJA)" },
    { value: "BVol", label: "Bulletin of Volcanology (BVol)" },
    { value: "SoEn", label: "Solar Energy (SoEn)" },
    { value: "SedG", label: "Sedimentary Geology (SedG)" },
    { value: "EGUGA", label: "EGU General Assembly Conference Abstracts (EGUGA)" },
    { value: "JMOp", label: "Journal of Modern Optics (JMOp)" },
    { value: "APh", label: "Astroparticle Physics (APh)" },
    { value: "PhT", label: "Physics Today (PhT)" },
    { value: "JGRE", label: "Journal of Geophysical Research (Planets) (JGRE)" },
    { value: "AmMin", label: "American Mineralogist (AmMin)" },
    { value: "ARNPS", label: "Annual Review of Nuclear and Particle Science (ARNPS)" },
    { value: "RvGSP", label: "Reviews of Geophysics and Space Physics (RvGSP)" },
    { value: "ESPL", label: "Earth Surface Processes and Landforms (ESPL)" },
    { value: "ScTEn", label: "Science of the Total Environment (ScTEn)" },
    { value: "ESRv", label: "Earth Science Reviews (ESRv)" },
    { value: "JRSp", label: "Journal of Raman Spectroscopy (JRSp)" },
    { value: "ASSL", label: "Astrophysics and Space Science Library (ASSL)" },
    { value: "JPoSB", label: "Journal of Polymer Science B Polymer Physics (JPoSB)" },
    { value: "IJMSI", label: "International Journal of Mass Spectrometry and Ion Processes (IJMSI)" },
    { value: "PApGe", label: "Pure and Applied Geophysics (PApGe)" },
    { value: "EPJD", label: "European Physical Journal D (EPJD)" },
    { value: "JPCRD", label: "Journal of Physical and Chemical Reference Data (JPCRD)" },
    { value: "ITAS", label: "IEEE Transactions on Applied Superconductivity (ITAS)" },
    { value: "M&PS", label: "Meteoritics and Planetary Science (M&PS)" },
    { value: "JAM", label: "Journal of Applied Mechanics (JAM)" },
    { value: "PrOce", label: "Progress in Oceanography (PrOce)" },
    { value: "JASTP", label: "Journal of Atmospheric and Solar-Terrestrial Physics (JASTP)" },
    { value: "EOSTr", label: "EOS Transactions (EOSTr)" },
    { value: "OptMa", label: "Optical Materials (OptMa)" },
    { value: "ESASP", label: "ESA Special Publication (ESASP)" },
    { value: "PhyE", label: "Physica E Low-Dimensional Systems and Nanostructures (PhyE)" },
    { value: "PMagA", label: "Philosophical Magazine, Part A (PMagA)" },
    { value: "PSST", label: "Plasma Sources Science Technology (PSST)" },
    { value: "PMagB", label: "Philosophical Magazine, Part B (PMagB)" },
    { value: "JHyMe", label: "Journal of Hydrometeorology (JHyMe)" },
    { value: "GPC", label: "Global and Planetary Change (GPC)" },
    { value: "BGeo", label: "Biogeosciences (BGeo)" },
    { value: "PhFlB", label: "Physics of Fluids B (PhFlB)" },
    { value: "MGeol", label: "Marine Geology (MGeol)" },
    { value: "DSRA", label: "Deep Sea Research A (DSRA)" },
    { value: "HESS", label: "Hydrology and Earth System Sciences (HESS)" },
    { value: "IJMPB", label: "International Journal of Modern Physics B (IJMPB)" },
    { value: "JChEd", label: "Journal of Chemical Education (JChEd)" },
    { value: "QuInt", label: "Quaternary International (QuInt)" },
    { value: "PhST", label: "Physica Scripta Volume T (PhST)" },
    { value: "Chaos", label: "Chaos (Chaos)" },
    { value: "MEPS", label: "Marine Ecology Progress Series (MEPS)" },
    { value: "OptSp", label: "Optics and Spectroscopy (OptSp)" },
    { value: "IJMPD", label: "International Journal of Modern Physics D (IJMPD)" },
    { value: "AdWR", label: "Advances in Water Resources (AdWR)" },
    { value: "HyInt", label: "Hyperfine Interactions (HyInt)" },
    { value: "JAESc", label: "Journal of Asian Earth Sciences (JAESc)" },
    { value: "AmJS", label: "American Journal of Science (AmJS)" },
    { value: "IAUC", label: "International Astronomical Union Circular (IAUC)" },
    { value: "PrPNP", label: "Progress in Particle and Nuclear Physics (PrPNP)" },
    { value: "RaPC", label: "Radiation Physics and Chemistry (RaPC)" },
    { value: "PThPS", label: "Progress of Theoretical Physics Supplement (PThPS)" },
    { value: "AAS", label: "American Astronomical Society Meeting Abstracts (AAS)" },
    { value: "JPhE", label: "Journal of Physics E Scientific Instruments (JPhE)" },
    { value: "PCPS", label: "Proceedings of the Cambridge Philosophical Society (PCPS)" },
    { value: "Cryo", label: "Cryogenics (Cryo)" },
    { value: "AnGla", label: "Annals of Glaciology (AnGla)" },
    { value: "IJTP", label: "International Journal of Theoretical Physics (IJTP)" },
    { value: "ITAES", label: "IEEE Transactions on Aerospace Electronic Systems (ITAES)" },
    { value: "SvPhU", label: "Soviet Physics Uspekhi (SvPhU)" },
    { value: "JSMTE", label: "Journal of Statistical Mechanics: Theory and Experiment (JSMTE)" },
    { value: "GSLSP", label: "Geological Society of London Special Publications (GSLSP)" },
    { value: "JDE", label: "Journal of Differential Equations (JDE)" },
    { value: "Chmsp", label: "Chemosphere (Chmsp)" },
    { value: "WtFor", label: "Weather and Forecasting (WtFor)" },
    { value: "JRScT", label: "Journal of Research in Science Teaching (JRScT)" },
    { value: "ArRMA", label: "Archive for Rational Mechanics and Analysis (ArRMA)" },
    { value: "JPlPh", label: "Journal of Plasma Physics (JPlPh)" },
    { value: "NCimB", label: "Nuovo Cimento B Serie (NCimB)" },
    { value: "CG", label: "Computers and Geosciences (CG)" },
    { value: "PhFlA", label: "Physics of Fluids A (PhFlA)" },
    { value: "SMaS", label: "Smart Material Structures (SMaS)" },
    { value: "GCBio", label: "Global Change Biology (GCBio)" },
    { value: "JMiMi", label: "Journal of Micromechanics and Microengineering (JMiMi)" },
    { value: "SuMi", label: "Superlattices and Microstructures (SuMi)" },
    { value: "SurSR", label: "Surface Science Reports (SurSR)" },
    { value: "ChPhB", label: "Chinese Physics B (ChPhB)" },
    { value: "TellB", label: "Tellus Series B Chemical and Physical Meteorology B (TellB)" },
    { value: "AcCrA", label: "Acta Crystallographica Section A (AcCrA)" },
    { value: "Oecol", label: "Oecologia (Oecol)" },
    { value: "AuJPh", label: "Australian Journal of Physics (AuJPh)" },
    { value: "BAAS", label: "Bulletin of the American Astronomical Society (BAAS)" },
    { value: "AgFM", label: "Agricultural and Forest Meteorology (AgFM)" },
    { value: "PCM", label: "Physics and Chemistry of Minerals (PCM)" },
    { value: "JMS", label: "Journal of Marine Systems (JMS)" },
    { value: "IJNMF", label: "International Journal for Numerical Methods in Fluids (IJNMF)" },
    { value: "JBO", label: "Journal of Biomedical Optics (JBO)" },
    { value: "ExFl", label: "Experiments in Fluids (ExFl)" },
    { value: "APExp", label: "Applied Physics Express (APExp)" },
    { value: "JRheo", label: "Journal of Rheology (JRheo)" },
    { value: "DSRI", label: "Deep Sea Research Part I: Oceanographic Research (DSRI)" },
    { value: "PPSA", label: "Proceedings of the Physical Society A (PPSA)" },
    { value: "ICRC", label: "International Cosmic Ray Conference (ICRC)" },
    { value: "LanB", label: "Landolt B&ouml;rnstein (LanB)" },
    { value: "AcA", label: "Acta Astronomica (AcA)" },
    { value: "PPP", label: "Palaeogeography Palaeoclimatology Palaeoecology (PPP)" },
    { value: "Tell", label: "Tellus (Tell)" },
    { value: "SciEd", label: "Science Education (SciEd)" },
    { value: "JMetG", label: "Journal of Metamorphic Geology (JMetG)" },
    { value: "PLSCB", label: "PLoS Computational Biology (PLSCB)" },
    { value: "IBVS", label: "Information Bulletin on Variable Stars (IBVS)" },
    { value: "Metro", label: "Metrologia (Metro)" },
    { value: "JGCD", label: "Journal of Guidance Control Dynamics (JGCD)" },
    { value: "AnRMS", label: "Annual Review of Materials Science (AnRMS)" },
    { value: "NatCC", label: "Nature Climate Change (NatCC)" },
    { value: "MTA", label: "Metallurgical Transactions A (MTA)" },
    { value: "ThApC", label: "Theoretical and Applied Climatology (ThApC)" },
    { value: "CzJPh", label: "Czechoslovak Journal of Physics (CzJPh)" },
    { value: "IJMSp", label: "International Journal of Mass Spectrometry (IJMSp)" },
    { value: "JSpRo", label: "Journal of Spacecraft and Rockets (JSpRo)" },
    { value: "Nonli", label: "Nonlinearity (Nonli)" },
    { value: "LaPhL", label: "Laser Physics Letters (LaPhL)" },
    { value: "LMaPh", label: "Letters in Mathematical Physics (LMaPh)" },
    { value: "RemS", label: "Remote Sensing (RemS)" },
    { value: "CCM", label: "Clays and Clay Minerals (CCM)" },
    { value: "SSASJ", label: "Soil Science Society of America Journal (SSASJ)" },
    { value: "IJBC", label: "International Journal of Bifurcation and Chaos (IJBC)" },
    { value: "Metic", label: "Meteoritics (Metic)" },
    { value: "PhSS", label: "Physics of the Solid State (PhSS)" },
    { value: "JGRF", label: "Journal of Geophysical Research (Earth Surface) (JGRF)" },
    { value: "ZPhyD", label: "Zeitschrift fur Physik D Atoms Molecules Clusters (ZPhyD)" },
    { value: "MSSP", label: "Mechanical Systems and Signal Processing (MSSP)" },
    { value: "IGRSL", label: "IEEE Geoscience and Remote Sensing Letters (IGRSL)" },
    { value: "InMat", label: "Inventiones Mathematicae (InMat)" },
    { value: "gr.qc", label: "ArXiv General Relativity and Quantum Cosmology e-prints (gr.qc)" },
    { value: "MMTA", label: "Metallurgical and Materials Transactions A (MMTA)" },
    { value: "EP&S", label: "Earth, Planets, and Space (EP&S)" },
    { value: "GeopP", label: "Geophysical Prospecting (GeopP)" },
    { value: "IJSEd", label: "International Journal of Science Education (IJSEd)" },
    { value: "FaDi", label: "Faraday Discussions (FaDi)" },
    { value: "AtmRe", label: "Atmospheric Research (AtmRe)" },
    { value: "InvPr", label: "Inverse Problems (InvPr)" },
    { value: "SvA", label: "Soviet Astronomy (SvA)" },
    { value: "SPhD", label: "Soviet Physics Doklady (SPhD)" },
    { value: "AcAau", label: "Acta Astronautica (AcAau)" },
    { value: "JCHyd", label: "Journal of Contaminant Hydrology (JCHyd)" },
    { value: "ForPh", label: "Fortschritte der Physik (ForPh)" },
    { value: "Vacuu", label: "Vacuum (Vacuu)" },
    { value: "JApMC", label: "Journal of Applied Meteorology and Climatology (JApMC)" },
    { value: "OptLT", label: "Optics Laser Technology (OptLT)" },
    { value: "STIN", label: "NASA STI/Recon Technical Report N (STIN)" },
    { value: "GCN", label: "GRB Coordinates Network (GCN)" },
    { value: "ER", label: "Environmental Research (ER)" },
    { value: "JPRS", label: "ISPRS Journal of Photogrammetry and Remote Sensing (JPRS)" },
    { value: "JAWRA", label: "Journal of the American Water Resources Association (JAWRA)" },
    { value: "JSedR", label: "Journal of Sedimentary Research (JSedR)" },
    { value: "ZhPmR", label: "ZhETF Pisma Redaktsiiu (ZhPmR)" },
    { value: "ERL", label: "Environmental Research Letters (ERL)" },
    { value: "PhRvS", label: "Physical Review Accelerators and Beams (PhRvS)" },
    { value: "ApPhy", label: "Applied Physics (ApPhy)" },
    { value: "PhyU", label: "Physics Uspekhi (PhyU)" },
    { value: "AuJES", label: "Australian Journal of Earth Sciences (AuJES)" },
    { value: "ATel", label: "The Astronomer's Telegram (ATel)" },
    { value: "AZh", label: "Astronomicheskii Zhurnal (AZh)" },
    { value: "PAN", label: "Physics of Atomic Nuclei (PAN)" },
    { value: "GApFD", label: "Geophysical and Astrophysical Fluid Dynamics (GApFD)" },
    { value: "PhRvX", label: "Physical Review X (PhRvX)" },
    { value: "SciAm", label: "Scientific American (SciAm)" },
    { value: "JQS", label: "Journal of Quaternary Science (JQS)" },
    { value: "Prama", label: "Pramana (Prama)" },
    { value: "BuSSA", label: "The Bulletin of the Seismological Society of America (BuSSA)" },
    { value: "GeoRu", label: "Geologische Rundschau (GeoRu)" },
    { value: "NRL", label: "Nanoscale Research Letters (NRL)" },
    { value: "AerST", label: "Aerosol Science Technology (AerST)" },
    { value: "ZhETF", label: "Zhurnal Eksperimentalnoi i Teoreticheskoi Fiziki (ZhETF)" },
    { value: "JGRG", label: "Journal of Geophysical Research (Biogeosciences) (JGRG)" },
    { value: "ElL", label: "Electronics Letters (ElL)" },
    { value: "JAfES", label: "Journal of African Earth Sciences (JAfES)" },
    { value: "RSPSB", label: "Proceedings of the Royal Society of London Series B (RSPSB)" },
    { value: "JInst", label: "Journal of Instrumentation (JInst)" },
    { value: "FoPh", label: "Foundations of Physics (FoPh)" },
    { value: "NewA", label: "New Astronomy (NewA)" },
    { value: "PSSCR", label: "Physica Status Solidi C Current Topics (PSSCR)" },
    { value: "NDS", label: "Nuclear Data Sheets (NDS)" },
    { value: "IAWPL", label: "IEEE Antennas and Wireless Propagation Letters (IAWPL)" },
    { value: "LPSC", label: "Lunar and Planetary Science Conference Proceedings (LPSC)" },
    { value: "NCim", label: "Il Nuovo Cimento (NCim)" },
    { value: "RSPTB", label: "Philosophical Transactions of the Royal Society of London Series B (RSPTB)" },
    { value: "JCoMa", label: "Journal of Composite Materials (JCoMa)" },
    { value: "Optik", label: "Optik (Optik)" },
    { value: "CNSNS", label: "Communications in Nonlinear Science and Numerical Simulations (CNSNS)" },
    { value: "OcMod", label: "Ocean Modelling (OcMod)" },
    { value: "NIMPR", label: "Nuclear Instruments and Methods in Physics Research (NIMPR)" },
    { value: "JAerS", label: "Journal of Aerosol Science (JAerS)" },
    { value: "ZA", label: "Zeitschrift fur Astrophysik (ZA)" },
    { value: "CoTPh", label: "Communications in Theoretical Physics (CoTPh)" },
    { value: "MPLB", label: "Modern Physics Letters B (MPLB)" },
    { value: "TMP", label: "Theoretical and Mathematical Physics (TMP)" },
    { value: "AcPPB", label: "Acta Physica Polonica B (AcPPB)" },
    { value: "AMM", label: "Applied Mechanics and Materials (AMM)" },
    { value: "Obs", label: "The Observatory (Obs)" },
    { value: "ConPh", label: "Contemporary Physics (ConPh)" },
    { value: "MAP", label: "Meteorology and Atmospheric Physics (MAP)" },
    { value: "JFS", label: "Journal of Fluids and Structures (JFS)" },
    { value: "AMT", label: "Atmospheric Measurement Techniques (AMT)" },
    { value: "PrSS", label: "Progress In Surface Science (PrSS)" },
    { value: "ISPM", label: "IEEE Signal Processing Magazine (ISPM)" },
    { value: "PMagL", label: "Philosophical Magazine Letters (PMagL)" },
    { value: "GondR", label: "Gondwana Research (GondR)" },
    { value: "LRR", label: "Living Reviews in Relativity (LRR)" },
    { value: "CeMDA", label: "Celestial Mechanics and Dynamical Astronomy (CeMDA)" },
    { value: "KvanE", label: "Kvantovaia Elektronika Moscow (KvanE)" },
    { value: "PhyBC", label: "Physica B+C (PhyBC)" },
    { value: "NPhS", label: "Nature Physical Science (NPhS)" },
    { value: "NHESS", label: "Natural Hazards and Earth System Sciences (NHESS)" },
    { value: "PPSB", label: "Proceedings of the Physical Society B (PPSB)" },
    { value: "GMS", label: "Washington DC American Geophysical Union Geophysical Monograph Series (GMS)" },
    { value: "HydJ", label: "Hydrogeology Journal (HydJ)" },
    { value: "Holoc", label: "The Holocene (Holoc)" },
    { value: "TellA", label: "Tellus Series A (TellA)" },
    { value: "JOptA", label: "Journal of Optics A: Pure and Applied Optics (JOptA)" },
    { value: "IEEEP", label: "IEEE Proceedings (IEEEP)" },
    { value: "JOpt", label: "Journal of Optics (JOpt)" },
    { value: "IJNLM", label: "International Journal of Non Linear Mechanics (IJNLM)" },
    { value: "JGeod", label: "Journal of Geodesy (JGeod)" },
    { value: "NatCh", label: "Nature Chemistry (NatCh)" },
    { value: "PlPh", label: "Plasma Physics (PlPh)" },
    { value: "MPEC", label: "Minor Planet Electronic Circulars (MPEC)" },
    { value: "ISPL", label: "IEEE Signal Processing Letters (ISPL)" },
    { value: "GeoM", label: "Geological Magazine (GeoM)" },
    { value: "LaPhy", label: "Laser Physics (LaPhy)" },
    { value: "CAP", label: "Current Applied Physics (CAP)" },
    { value: "SSSci", label: "Solid State Sciences (SSSci)" },
    { value: "JScI", label: "Journal of Scientific Instruments (JScI)" },
    { value: "BJAP", label: "British Journal of Applied Physics (BJAP)" },
    { value: "CorRe", label: "Coral Reefs (CorRe)" },
    { value: "RuMaS", label: "Russian Mathematical Surveys (RuMaS)" },
    { value: "ZaMM", label: "Zeitschrift Angewandte Mathematik und Mechanik (ZaMM)" },
    { value: "Semic", label: "Semiconductors (Semic)" },
    { value: "IJMPE", label: "International Journal of Modern Physics E (IJMPE)" },
    { value: "GMD", label: "Geoscientific Model Development (GMD)" },
    { value: "CompM", label: "Computational Mechanics (CompM)" },
    { value: "IJMPC", label: "International Journal of Modern Physics C (IJMPC)" },
    { value: "AstL", label: "Astronomy Letters (AstL)" },
    { value: "AcOpt", label: "Optica Acta (AcOpt)" },
    { value: "JPoSc", label: "Journal of Polymer Science (JPoSc)" },
    { value: "A&ARv", label: "Astronomy and Astrophysics Review (A&ARv)" },
    { value: "JGP", label: "Journal of Geometry and Physics (JGP)" },
    { value: "Geode", label: "Geofisica Internacional (Geode)" },
    { value: "MinM", label: "Mineralogical Magazine (MinM)" },
    { value: "PhTea", label: "The Physics Teacher (PhTea)" },
    { value: "MmSAI", label: "Memorie della Societa Astronomica Italiana (MmSAI)" },
    { value: "TCry", label: "The Cryosphere (TCry)" },
    { value: "NewAR", label: "New Astronomy Reviews (NewAR)" },
    { value: "MT", label: "Metallurgical Transactions (MT)" },
    { value: "ApL", label: "Astrophysical Letters (ApL)" },
    { value: "PASA", label: "Publications of the Astronomical Society of Australia (PASA)" },
    { value: "MSMSE", label: "Modelling Simul. Mater. Sci. Eng. (MSMSE)" },
    { value: "IJEaS", label: "International Journal of Earth Sciences (IJEaS)" },
    { value: "ASIC", label: "NATO Advanced Science Institutes (ASI) Series C (ASIC)" },
    { value: "AdTMP", label: "Advances in Theoretical and Mathematical Physics (AdTMP)" },
    { value: "MPC", label: "Minor Planet Circulars (MPC)" },
    { value: "IJT", label: "International Journal of Thermophysics (IJT)" },
    { value: "MinDe", label: "Mineralium Deposita (MinDe)" },
    { value: "OptLE", label: "Optics and Lasers in Engineering (OptLE)" },
    { value: "ACPD", label: "Atmospheric Chemistry & Physics Discussions (ACPD)" },
    { value: "Wthr", label: "Weather (Wthr)" },
    { value: "ChPhy", label: "Chinese Physics (ChPhy)" },
    { value: "CeMec", label: "Celestial Mechanics (CeMec)" },
    { value: "TePhL", label: "Technical Physics Letters (TePhL)" },
    { value: "JOM", label: "JOM - Journal of the Minerals, Metals and Materials Society (JOM)" },
    { value: "JNR", label: "Journal of Nanoparticle Research (JNR)" },
    { value: "BAN", label: "Bulletin of the Astronomical Institutes of the Netherlands (BAN)" },
    { value: "AIPA", label: "AIP Advances (AIPA)" },
    { value: "JSAES", label: "Journal of South American Earth Sciences (JSAES)" },
    { value: "LTP", label: "Low Temperature Physics (LTP)" },
    { value: "TeNov", label: "Terra Nova (TeNov)" },
    { value: "CoPP", label: "Contributions to Plasma Physics (CoPP)" },
    { value: "JAG", label: "Journal of Applied Geophysics (JAG)" },
    { value: "SIAMR", label: "SIAM Review (SIAMR)" },
    { value: "AsBio", label: "Astrobiology (AsBio)" },
    { value: "Ge&Ae", label: "Geomagnetism and Aeronomy (Ge&Ae)" },
    { value: "SJNA", label: "SIAM Journal on Numerical Analysis (SJNA)" },
    { value: "MiMic", label: "Microscopy and Microanalysis (MiMic)" },
    { value: "LPB", label: "Laser and Particle Beams (LPB)" },
    { value: "ChSBu", label: "Chinese Science Bulletin (ChSBu)" },
    { value: "EPJE", label: "European Physical Journal E (EPJE)" },
    { value: "NHTA", label: "Numerical Heat Transfer Part A - Applications (NHTA)" },
    { value: "MS&E", label: "Materials Science and Engineering Conference Series (MS&E)" },
    { value: "JKPS", label: "Journal of Korean Physical Society (JKPS)" },
    { value: "ZK", label: "Zeitschrift fur Kristallographie (ZK)" },
    { value: "AdAtS", label: "Advances in Atmospheric Sciences (AdAtS)" },
    { value: "JGG", label: "Journal of Geomagnetism and Geoelectricity (JGG)" },
    { value: "ChPhC", label: "Chinese Physics C (ChPhC)" },
    { value: "SvAL", label: "Soviet Astronomy Letters (SvAL)" },
    { value: "ZaMP", label: "Zeitschrift Angewandte Mathematik und Physik (ZaMP)" },
    { value: "AnAp", label: "Annales d'Astrophysique (AnAp)" },
    { value: "EPJST", label: "European Physical Journal Special Topics (EPJST)" },
    { value: "RpMP", label: "Reports on Mathematical Physics (RpMP)" },
    { value: "JOptB", label: "Journal of Optics B: Quantum and Semiclassical Optics (JOptB)" },
    { value: "GML", label: "Geo-Marine Letters (GML)" },
    { value: "Msngr", label: "The Messenger (Msngr)" },
    { value: "CliPa", label: "Climate of the Past (CliPa)" },
    { value: "InfPh", label: "Infrared Physics (InfPh)" },
    { value: "SPIE1", label: "Society of Photo-Optical Instrumentation Engineers (SPIE) Conference Series (SPIE1)" },
    { value: "JGeo", label: "Journal of Geodynamics (JGeo)" },
    { value: "RMxAA", label: "Revista Mexicana de Astronomia y Astrofisica (RMxAA)" },
    { value: "R&QE", label: "Radiophysics and Quantum Electronics (R&QE)" },
    { value: "IJAEO", label: "International Journal of Applied Earth Observation and Geoinformation (IJAEO)" },
    { value: "RadR", label: "Radiation Research (RadR)" },
    { value: "JTST", label: "Journal of Thermal Spray Technology (JTST)" },
    { value: "PlPhR", label: "Plasma Physics Reports (PlPhR)" },
    { value: "yCat", label: "VizieR Online Data Catalog (yCat)" },
    { value: "Mate", label: "Materials (Mate)" },
    { value: "ITNan", label: "IEEE Transactions on Nanotechnology (ITNan)" },
    { value: "IJBm", label: "International Journal of Biometeorology (IJBm)" },
    { value: "WASP", label: "Water Air and Soil Pollution (WASP)" },
    { value: "EM&P", label: "Earth Moon and Planets (EM&P)" },
    { value: "S&T", label: "Sky and Telescope (S&T)" },
    { value: "IJSSC", label: "IEEE Journal of Solid-State Circuits (IJSSC)" },
    { value: "ApMRv", label: "Applied Mechanics Reviews (ApMRv)" },
    { value: "ARep", label: "Astronomy Reports (ARep)" },
    { value: "DPS", label: "AAS/Division for Planetary Sciences Meeting Abstracts (DPS)" },
    { value: "InPhT", label: "Infrared Physics and Technology (InPhT)" },
    { value: "NPGeo", label: "Nonlinear Processes in Geophysics (NPGeo)" },
    { value: "IJIMW", label: "International Journal of Infrared and Millimeter Waves (IJIMW)" },
    { value: "SGeo", label: "Surveys in Geophysics (SGeo)" },
    { value: "EPJWC", label: "European Physical Journal Web of Conferences (EPJWC)" },
    { value: "FBS", label: "Few-Body Systems (FBS)" },
    { value: "PCE", label: "Physics and Chemistry of the Earth (PCE)" },
    { value: "MinPe", label: "Mineralogy and Petrology (MinPe)" },
    { value: "IJQC", label: "International Journal of Quantum Chemistry (IJQC)" },
    { value: "CaJRS", label: "Canadian Journal of Remote Sensing (CaJRS)" },
    { value: "CRPhy", label: "Comptes Rendus Physique (CRPhy)" },
    { value: "JRASC", label: "Journal of the Royal Astronomical Society of Canada (JRASC)" },
    { value: "JTePh", label: "Journal of Technical Physics (JTePh)" },
    { value: "IGRv", label: "International Geology Review (IGRv)" },
    { value: "OcDyn", label: "Ocean Dynamics (OcDyn)" },
    { value: "DyAtO", label: "Dynamics of Atmospheres and Oceans (DyAtO)" },
    { value: "JCoAM", label: "Journal of Computational and Applied Mathematics (JCoAM)" },
    { value: "JSR", label: "Journal of Sea Research (JSR)" },
    { value: "TrAGU", label: "Transactions, American Geophysical Union (TrAGU)" },
    { value: "RuCRv", label: "Russian Chemical Reviews (RuCRv)" },
    { value: "RadM", label: "Radiation Measurements (RadM)" },
    { value: "JMolE", label: "Journal of Molecular Evolution (JMolE)" },
    { value: "AdAMP", label: "Advances in Atomic and Molecular Physics (AdAMP)" },
    { value: "LPICo", label: "LPI Contributions (LPICo)" },
    { value: "Afz", label: "Astrofizika (Afz)" },
    { value: "BAICz", label: "Bulletin of the Astronomical Institutes of Czechoslovakia (BAICz)" },
    { value: "IAPM", label: "IEEE Antennas and Propagation Magazine (IAPM)" },
    { value: "EJPh", label: "European Journal of Physics (EJPh)" },
    { value: "JPhy1", label: "Journal de Physique I (JPhy1)" },
    { value: "PhPro", label: "Physics Procedia (PhPro)" },
    { value: "PQE", label: "Progress in Quantum Electronics (PQE)" },
    { value: "Entrp", label: "Entropy (Entrp)" },
    { value: "SoilS", label: "Soil Science (SoilS)" },
    { value: "EPJAP", label: "European Physical Journal Applied Physics (EPJAP)" },
    { value: "BrJPh", label: "Brazilian Journal of Physics (BrJPh)" },
    { value: "HPR", label: "High Pressure Research (HPR)" },
    { value: "SbMat", label: "Sbornik: Mathematics (SbMat)" },
    { value: "JApSp", label: "Journal of Applied Spectroscopy (JApSp)" },
    { value: "AGUSM", label: "AGU Spring Meeting Abstracts (AGUSM)" },
    { value: "EnGeo", label: "Environmental Geology (EnGeo)" },
    { value: "MmRAS", label: "Memoirs of the Royal Astronomical Society (MmRAS)" },
    { value: "EnMan", label: "Environmental Management (EnMan)" },
    { value: "COSSM", label: "Current Opinion in Solid State and Materials Science (COSSM)" },
    { value: "CRGeo", label: "Comptes Rendus Geoscience (CRGeo)" },
    { value: "IAM", label: "International Applied Mechanics (IAM)" },
    { value: "AdQC", label: "Advances in Quantum Chemistry (AdQC)" },
    { value: "RvMG", label: "Reviews in Mineralogy and Geochemistry (RvMG)" },
    { value: "AAMOP", label: "Advances in Atomic Molecular and Optical Physics (AAMOP)" },
    { value: "RCMS", label: "Rapid Communications in Mass Spectrometry (RCMS)" },
    { value: "EJMin", label: "European Journal of Mineralogy (EJMin)" },
    { value: "QJRAS", label: "Quarterly Journal of the Royal Astronomical Society (QJRAS)" },
    { value: "SciA", label: "Science Advances (SciA)" },
    { value: "JMEP", label: "Journal of Materials Engineering and Performance (JMEP)" },
    { value: "JSup", label: "Journal of Superconductivity (JSup)" },
    { value: "MTB", label: "Metallurgical Transactions B (MTB)" },
    { value: "NCimC", label: "Nuovo Cimento C Geophysics Space Physics C (NCimC)" },
    { value: "NASSP", label: "NASA Special Publication (NASSP)" },
    { value: "NHTB", label: "Numerical Heat Transfer Part B - Fundamentals (NHTB)" },
    { value: "JAMTP", label: "Journal of Applied Mechanics and Technical Physics (JAMTP)" },
    { value: "ITPE", label: "IEEE Transactions on Power Electronics (ITPE)" },
    { value: "ClMin", label: "Clay Minerals (ClMin)" },
    { value: "SpecL", label: "Spectroscopy Letters (SpecL)" },
    { value: "JAtC", label: "Journal of Atmospheric Chemistry (JAtC)" },
    { value: "PrAeS", label: "Progress in Aerospace Sciences (PrAeS)" },
    { value: "MMAS", label: "Mathematical Methods in the Applied Sciences (MMAS)" },
    { value: "DoSSR", label: "Akademiia Nauk SSSR Doklady (DoSSR)" },
    { value: "JBAA", label: "Journal of the British Astronomical Association (JBAA)" },
    { value: "VA", label: "Vistas in Astronomy (VA)" },
    { value: "MarMP", label: "Marine Micropaleontology (MarMP)" },
    { value: "IJNAM", label: "International Journal for Numerical and Analytical Methods in Geomechanics (IJNAM)" },
    { value: "PhyEd", label: "Physics Education (PhyEd)" },
    { value: "OLEB", label: "Origins of Life and Evolution of the Biosphere (OLEB)" },
    { value: "RAA", label: "Research in Astronomy and Astrophysics (RAA)" },
    { value: "STAdM", label: "Science and Technology of Advanced Materials (STAdM)" },
    { value: "QuIP", label: "Quantum Information Processing (QuIP)" },
    { value: "MMTB", label: "Metallurgical and Materials Transactions B (MMTB)" },
    { value: "BasR", label: "Basin Research (BasR)" },
    { value: "PSSRR", label: "Physica Status Solidi Rapid Research Letters (PSSRR)" },
    { value: "SpWea", label: "Space Weather (SpWea)" },
    { value: "SCPMA", label: "Science China Physics, Mechanics, and Astronomy (SCPMA)" },
    { value: "ARCMP", label: "Annual Review of Condensed Matter Physics (ARCMP)" },
    { value: "JCAMD", label: "Journal of Computer-Aided Molecular Design (JCAMD)" },
    { value: "FlDyR", label: "Fluid Dynamics Research (FlDyR)" },
    { value: "ITPSy", label: "IEEE Transactions on Power Systems (ITPSy)" },
    { value: "DokES", label: "Doklady Earth Sciences (DokES)" },
    { value: "OptFT", label: "Optical Fiber Technology (OptFT)" },
    { value: "EJMF", label: "European Journal of Mechanics B Fluids (EJMF)" },
    { value: "CryRp", label: "Crystallography Reports (CryRp)" },
    { value: "IJCA", label: "International Journal of Computer Applications (IJCA)" },
    { value: "JPhy2", label: "Journal de Physique II (JPhy2)" },
    { value: "MeApp", label: "Meteorological Applications (MeApp)" },
    { value: "ISTSP", label: "IEEE Journal of Selected Topics in Signal Processing (ISTSP)" },
    { value: "JMSp", label: "Journal of Mass Spectrometry (JMSp)" },
    { value: "REDS", label: "Radiation Effects and Defects in Solids (REDS)" },
    { value: "JGSoc", label: "Journal of the Geological Society (JGSoc)" },
    { value: "PASAu", label: "Proceedings of the Astronomical Society of Australia (PASAu)" },
    { value: "IJSTQ", label: "IEEE Journal of Selected Topics in Quantum Electronics (IJSTQ)" },
    { value: "JApMM", label: "Journal of Applied Mathematics and Mechanics (JApMM)" },
    { value: "AdGeo", label: "Advances in Geophysics (AdGeo)" },
    { value: "MaCom", label: "Mathematics of Computation (MaCom)" },
    { value: "JDisT", label: "Journal of Display Technology (JDisT)" },
    { value: "ApGC", label: "Applied Geochemistry (ApGC)" },
    { value: "ClRes", label: "Climate Research (ClRes)" },
    { value: "E&ES", label: "IOP Conference Series: Earth and Environmental Science (E&ES)" },
    { value: "JApA", label: "Journal of Astrophysics and Astronomy (JApA)" },
    { value: "NCimD", label: "Nuovo Cimento D Serie (NCimD)" },
    { value: "JArEn", label: "Journal of Arid Environments (JArEn)" },
    { value: "GeCAS", label: "Geochimica et Cosmochimica Acta Supplement (GeCAS)" },
    { value: "ExA", label: "Experimental Astronomy (ExA)" },
    { value: "AnHP", label: "Annales Henri Poincar&eacute; (AnHP)" },
    { value: "FlDy", label: "Fluid Dynamics (FlDy)" },
    { value: "JJAPS", label: "Japanese Journal of Applied Physics Supplement (JJAPS)" },
    { value: "DSR", label: "Deep Sea Research (DSR)" },
    { value: "IRPC", label: "International Reviews in Physical Chemistry (IRPC)" },
    { value: "EJMS", label: "European Journal of Mechanics Solids (EJMS)" },
    { value: "HMT", label: "Heat and Mass Transfer (HMT)" },
    { value: "PA", label: "Popular Astronomy (PA)" },
    { value: "SPTP", label: "Soviet Physics Technical Physics (SPTP)" },
    { value: "CBET", label: "Central Bureau Electronic Telegrams (CBET)" },
    { value: "C&T", label: "Ciel et Terre (C&T)" },
    { value: "MPCPS", label: "Mathematical Proceedings of the Cambridge Philosophical Society (MPCPS)" },
    { value: "CRSSM", label: "Critical Reviews in Solid State & Materials Sciences (CRSSM)" },
    { value: "JMSB", label: "Journal of Macromolecular Science, Part B (JMSB)" },
    { value: "RvMaP", label: "Reviews in Mathematical Physics (RvMaP)" },
    { value: "NJSR", label: "Netherlands Journal of Sea Research (NJSR)" },
    { value: "JNEng", label: "Journal of Neural Engineering (JNEng)" },
    { value: "JAMES", label: "Journal of Advances in Modeling Earth Systems (JAMES)" },
    { value: "JPoSL", label: "Journal of Polymer Science: Polymer Letters Edition (JPoSL)" },
    { value: "WiEn", label: "Wind Energy (WiEn)" },
    { value: "RuPhJ", label: "Russian Physics Journal (RuPhJ)" },
    { value: "MetZe", label: "Meteorologische Zeitschrift (MetZe)" },
    { value: "JCP", label: "Journal de Chimie Physique (JCP)" },
    { value: "ThCFD", label: "Theoretical and Computational Fluid Dynamics (ThCFD)" },
    { value: "PhRvP", label: "Physical Review Applied (PhRvP)" },
    { value: "ESOC", label: "European Southern Observatory Conference and Workshop Proceedings (ESOC)" },
    { value: "ShWav", label: "Shock Waves (ShWav)" },
    { value: "EAEJA", label: "EGS - AGU - EUG Joint Assembly (EAEJA)" },
    { value: "PKM", label: "Physik der Kondensierten Materie (PKM)" },
    { value: "PAZh", label: "Pisma v Astronomicheskii Zhurnal (PAZh)" },
    { value: "OcSci", label: "Ocean Science (OcSci)" },
    { value: "JASMS", label: "Journal of The American Society for Mass Spectrometry (JASMS)" },
    { value: "StGG", label: "Studia Geophysica et Geodaetica (StGG)" },
    { value: "RScEd", label: "Research in Science Education (RScEd)" },
    { value: "IzMat", label: "Izvestiya: Mathematics (IzMat)" },
    { value: "PhyM", label: "Physiological Measurement (PhyM)" },
    { value: "RSPT", label: "Philosophical Transactions of the Royal Society of London Series I (RSPT)" },
    { value: "BaltA", label: "Baltic Astronomy (BaltA)" },
    { value: "MSHT", label: "Metal Science and Heat Treatment (MSHT)" },
    { value: "Moon", label: "Moon (Moon)" },
    { value: "EPJP", label: "European Physical Journal Plus (EPJP)" },
    { value: "BASI", label: "Bulletin of the Astronomical Society of India (BASI)" },
    { value: "RMxAC", label: "Revista Mexicana de Astronomia y Astrofisica Conference Series (RMxAC)" },
    { value: "BGD", label: "Biogeosciences Discussions (BGD)" },
    { value: "ITEdu", label: "IEEE Transactions on Education (ITEdu)" },
    { value: "OptRv", label: "Optical Review (OptRv)" },
    { value: "SRL", label: "Surface Review and Letters (SRL)" },
    { value: "JNS", label: "Journal of NonLinear Science (JNS)" },
    { value: "LAstr", label: "L'Astronomie (LAstr)" },
    { value: "SvPhJ", label: "Soviet Physics Journal (SvPhJ)" },
    { value: "PlST", label: "Plasma Science and Technology (PlST)" },
    { value: "Geosp", label: "Geosphere (Geosp)" },
    { value: "Ap", label: "Astrophysics (Ap)" },
    { value: "JElS", label: "Journal of the Electrochemical Society (JElS)" },
    { value: "DokPh", label: "Physics - Doklady (DokPh)" },
    { value: "FCPh", label: "Fundamentals of Cosmic Physics (FCPh)" },
    { value: "MSRv", label: "Mass Spectrometry Reviews (MSRv)" },
    { value: "MarGR", label: "Marine Geophysical Research (MarGR)" },
    { value: "NDT", label: "Nuclear Data Tables (NDT)" },
    { value: "NASCP", label: "NASA Conference Publication (NASCP)" },
    { value: "SurSL", label: "Surface Science Letters (SurSL)" },
    { value: "ISenJ", label: "IEEE Sensors Journal (ISenJ)" },
    { value: "JEnMa", label: "Journal of Engineering Mathematics (JEnMa)" },
    { value: "RMRE", label: "Rock Mechanics and Rock Engineering (RMRE)" },
    { value: "HDP", label: "Handbuch der Physik (HDP)" },
    { value: "LRSP", label: "Living Reviews in Solar Physics (LRSP)" },
    { value: "PTEP", label: "Progress of Theoretical and Experimental Physics (PTEP)" },
    { value: "PhBio", label: "Physical Biology (PhBio)" },
    { value: "AmSci", label: "American Scientist (AmSci)" },
    { value: "JSeis", label: "Journal of Seismology (JSeis)" },
    { value: "AcMSn", label: "Acta Mechanica Sinica (AcMSn)" },
    { value: "Palai", label: "PALAIOS (Palai)" },
    { value: "OptPN", label: "Optics & Photonics News (OptPN)" },
    { value: "LNCS", label: "Lecture Notes in Computer Science (LNCS)" },
    { value: "GrCo", label: "Gravitation and Cosmology (GrCo)" },
    { value: "UsFiN", label: "Uspekhi Fizicheskikh Nauk (UsFiN)" },
    { value: "RJPCA", label: "Russian Journal of Physical Chemistry A (RJPCA)" },
    { value: "IJTPE", label: "IEEJ Transactions on Power and Energy (IJTPE)" },
    { value: "ARMS", label: "Annual Review of Marine Science (ARMS)" },
    { value: "SIGMA", label: "SIGMA (SIGMA)" },
    { value: "CoPhR", label: "Computer Physics Reports (CoPhR)" },
    { value: "ECMS", label: "Estuarine and Coastal Marine Science (ECMS)" },
    { value: "CMT", label: "Continuum Mechanics and Thermodynamics (CMT)" },
    { value: "APhy", label: "Acoustical Physics (APhy)" },
    { value: "ApSRv", label: "Applied Spectroscopy Reviews (ApSRv)" },
    { value: "Sc&Ed", label: "Science & Education (Sc&Ed)" },
    { value: "ChOpL", label: "Chinese Optics Letters (ChOpL)" },
    { value: "PDiff", label: "Powder Diffraction (PDiff)" },
    { value: "AnPh", label: "Annales de Physique (AnPh)" },
    { value: "HEDP", label: "High Energy Density Physics (HEDP)" },
    { value: "SoSyR", label: "Solar System Research (SoSyR)" },
    { value: "ITPAS", label: "IEEE Transactions on Power Apparatus Systems (ITPAS)" },
    { value: "prpl.conf", label: "Protostars and Planets (prpl.conf)" },
    { value: "NCimR", label: "Nuovo Cimento Rivista Serie (NCimR)" },
    { value: "AAM", label: "Archive of Applied Mechanics (AAM)" },
    { value: "PDAO", label: "Publications of the Dominion Astrophysical Observatory Victoria (PDAO)" },
    { value: "JPall", label: "Journal of Palaeolimnology (JPall)" },
    { value: "RaF", label: "Radiofizika (RaF)" },
    { value: "EJASP", label: "EURASIP Journal on Applied Signal Processing (EJASP)" },
    { value: "RuGG", label: "Russian Geology and Geophysics (RuGG)" },
    { value: "JEI", label: "Journal of Electronic Imaging (JEI)" },
    { value: "TSICE", label: "Transactions of the Society of Instrument and Control Engineers (TSICE)" },
    { value: "HTrEn", label: "Heat Transfer Engineering (HTrEn)" },
    { value: "ATsir", label: "Astronomicheskij Tsirkulyar (ATsir)" },
    { value: "ClCh", label: "Climatic Change (ClCh)" },
    { value: "SciMo", label: "The Scientific Monthly (SciMo)" },
    { value: "InJPh", label: "Indian Journal of Physics (InJPh)" },
    { value: "HESSD", label: "Hydrology and Earth System Sciences Discussions (HESSD)" },
    { value: "SAOSR", label: "SAO Special Report (SAOSR)" },
    { value: "JEP", label: "Journal of Engineering Physics (JEP)" },
    { value: "IJTFM", label: "IEEJ Transactions on Fundamentals and Materials (IJTFM)" },
    { value: "AD", label: "Atomic Data (AD)" },
    { value: "ITEIS", label: "IEEJ Transactions on Electronics, Information and Systems (ITEIS)" },
    { value: "WRM", label: "Waves in Random Media (WRM)" },
    { value: "PZETF", label: "Pisma v Zhurnal Eksperimentalnoi i Teoreticheskoi Fiziki (PZETF)" },
    { value: "HiA", label: "Highlights of Astronomy (HiA)" },
    { value: "CRASM", label: "Academie des Sciences Paris Comptes Rendus Serie Sciences Mathematiques (CRASM)" },
    { value: "AIHPC", label: "Annales de L'Institut Henri Poincare Section (C) Non Linear Analysis (AIHPC)" },
    { value: "CosRe", label: "Cosmic Research (CosRe)" },
    { value: "MsT", label: "Masters Thesis (MsT)" },
    { value: "NCimL", label: "Nuovo Cimento Lettere (NCimL)" },
    { value: "FizPl", label: "Fizika Plazmy (FizPl)" },
    { value: "ISPAr", label: "ISPRS - International Archives of the Photogrammetry, Remote Sensing and Spatial Information Sciences (ISPAr)" },
    { value: "AcO", label: "Acta Oecologica (AcO)" },
    { value: "JESS", label: "Journal of Earth System Science (JESS)" },
    { value: "JTurb", label: "Journal of Turbulence (JTurb)" },
    { value: "APLM", label: "APL Materials (APLM)" },
    { value: "IJTIA", label: "IEEJ Transactions on Industry Applications (IJTIA)" },
    { value: "JMAA", label: "Journal of Mathematical Analysis and Applications (JMAA)" },
    { value: "JNOPM", label: "Journal of Nonlinear Optical Physics and Materials (JNOPM)" },
    { value: "JNET", label: "Journal of Non Equilibrium Thermodynamics (JNET)" },
    { value: "SScEd", label: "Studies in Science Education (SScEd)" },
    { value: "MRE", label: "Materials Research Express (MRE)" },
    { value: "TDM", label: "2D Materials (TDM)" },
    { value: "ComPh", label: "Computers in Physics (ComPh)" },
    { value: "IEITE", label: "IEICE Transactions on Electronics (IEITE)" },
    { value: "JApSc", label: "Journal of Applied Sciences (JApSc)" },
    { value: "M&PSA", label: "Meteoritics and Planetary Science Supplement (M&PSA)" },
    { value: "PFR", label: "Plasma and Fusion Research (PFR)" },
    { value: "RaEl", label: "Radiotekhnika i Elektronika (RaEl)" },
    { value: "AcASn", label: "Acta Astronomica Sinica (AcASn)" },
    { value: "ChJAA", label: "Chinese Journal of Astronomy and Astrophysics (ChJAA)" },
    { value: "TTSP", label: "Transport Theory and Statistical Physics (TTSP)" },
    { value: "JSemi", label: "Journal of Semiconductors (JSemi)" },
    { value: "RSPS", label: "Proceedings of the Royal Society of London Series I (RSPS)" },
    { value: "XRS", label: "X-ray Spectrometry (XRS)" },
    { value: "CEJPh", label: "Central European Journal of Physics (CEJPh)" },
    { value: "AtScL", label: "Atmospheric Science Letters (AtScL)" },
    { value: "JPhy4", label: "Journal de Physique IV (JPhy4)" },
    { value: "KosIs", label: "Kosmicheskie Issledovaniia (KosIs)" },
    { value: "BRASP", label: "Bulletin of the Russian Academy of Sciences, Physics (BRASP)" },
    { value: "PolRe", label: "National Institute Polar Research Memoirs (PolRe)" },
    { value: "JNIS", label: "Journal of Near Infrared Spectroscopy (JNIS)" },
    { value: "PMM", label: "Physics of Metals and Metallography (PMM)" },
    { value: "PDU", label: "Physics of the Dark Universe (PDU)" },
    { value: "SvApM", label: "Soviet Applied Mechanics (SvApM)" },
    { value: "CRMec", label: "Comptes Rendus Mecanique (CRMec)" },
    { value: "MNSSA", label: "Monthly Notes of the Astronomical Society of South Africa (MNSSA)" },
    { value: "OrLi", label: "Origins of Life (OrLi)" },
    { value: "ScChA", label: "Science in China A: Mathematics (ScChA)" },
    { value: "PRPER", label: "Physical Review Physics Education Research (PRPER)" },
    { value: "IEITC", label: "IEICE Transactions on Communications (IEITC)" },
    { value: "JVSJ", label: "Journal of the Vacuum Society of Japan (JVSJ)" },
    { value: "EurSS", label: "Eurasian Soil Science (EurSS)" },
    { value: "IPhoJ", label: "IEEE Photonics Journal (IPhoJ)" },
    { value: "PhNan", label: "Photonics and Nanostructures (PhNan)" },
    { value: "ITTST", label: "IEEE Transactions on Terahertz Science and Technology (ITTST)" },
    { value: "ChJOL", label: "Chinese Journal of Oceanology and Limnology (ChJOL)" },
    { value: "CRASB", label: "Academie des Sciences Paris Comptes Rendus Serie B Sciences Physiques (CRASB)" },
    { value: "JFuE", label: "Journal of Funsion Energy (JFuE)" },
    { value: "DSROA", label: "Deep Sea Research and Oceanographic Abstracts (DSROA)" },
    { value: "RadEf", label: "Radiation Effects (RadEf)" },
    { value: "JSTEd", label: "Journal of Science Teacher Education (JSTEd)" },
    { value: "M&P", label: "Moon and Planets (M&P)" },
    { value: "JRPC", label: "Journal of Reinforced Plastics and Composites (JRPC)" },
    { value: "STMP", label: "Springer Tracts in Modern Physics (STMP)" },
    { value: "AntSc", label: "Antarctic Science (AntSc)" },
    { value: "RvPP", label: "Reviews of Plasma Physics (RvPP)" },
    { value: "JAVSO", label: "Journal of the American Association of Variable Star Observers (JAAVSO) (JAVSO)" },
    { value: "JBIS", label: "Journal of the British Interplanetary Society (JBIS)" },
    { value: "ASSP", label: "Astrophysics and Space Science Proceedings (ASSP)" },
    { value: "QJMat", label: "The Quarterly Journal of Mathematics (QJMat)" },
    { value: "MitAG", label: "Mitteilungen der Astronomischen Gesellschaft Hamburg (MitAG)" },
    { value: "PhyOJ", label: "Physics Online Journal (PhyOJ)" },
    { value: "JKAS", label: "Journal of Korean Astronomical Society (JKAS)" },
    { value: "JNMP", label: "Journal of Nonlinear Mathematical Physics (JNMP)" },
    { value: "IJHMT", label: "International Journal of Heat and Mass Transfer (IJHMT)" },
    { value: "GeoPA", label: "Geofisica Pura e Applicata (GeoPA)" },
    { value: "TeMAE", label: "Terrestrial Magnetism and Atmospheric Electricity (Journal of Geophysical Research) (TeMAE)" },
    { value: "ITEnC", label: "IEEE Transactions on Energy Conversion (ITEnC)" },
    { value: "BGeod", label: "Bulletin Geodesique (BGeod)" },
    { value: "PhRvI", label: "Physical Review Series I (PhRvI)" },
    { value: "JAChS", label: "Journal of the American Chemical Society (JAChS)" },
    { value: "ESSD", label: "Earth System Science Data (ESSD)" },
    { value: "IEITF", label: "IEICE Transactions on Fundamentals of Electronics Communications and Computer Sciences (IEITF)" },
    { value: "PApOp", label: "Pure Applied Optics (PApOp)" },
    { value: "TrGeo", label: "Treatise on Geochemistry (TrGeo)" },
    { value: "CTM", label: "Combustion Theory and Modelling (CTM)" },
    { value: "Lsphe", label: "Lithoshere (Lsphe)" },
    { value: "ChA&A", label: "Chinese Astronomy and Astrophysics (ChA&A)" },
    { value: "JDDE", label: "Journal of Dynamics and Differential Equations (JDDE)" },
    { value: "A&AT", label: "Astronomical and Astrophysical Transactions (A&AT)" },
    { value: "JSEdT", label: "Journal of Science Education and Technology (JSEdT)" },
    { value: "LIACo", label: "Liege International Astrophysical Colloquia (LIACo)" },
    { value: "PPN", label: "Physics of Particles and Nuclei (PPN)" },
    { value: "JARS", label: "Journal of Applied Remote Sensing (JARS)" },
    { value: "AnMat", label: "Annals of Mathematics (AnMat)" },
    { value: "SoEnM", label: "Solar Energy Materials (SoEnM)" },
    { value: "AcPPA", label: "Acta Physica Polonica A (AcPPA)" },
    { value: "CoAst", label: "Communications in Asteroseismology (CoAst)" },
    { value: "ScChG", label: "Science in China: Physics, Mechanics and Astronomy (ScChG)" },
    { value: "AcGeo", label: "Acta Geophysica (AcGeo)" },
    { value: "JNuE", label: "Journal of Nuclear Energy (JNuE)" },
    { value: "JEPT", label: "Journal of Engineering Physics and Thermophysics (JEPT)" },
    { value: "IzAOP", label: "Izvestiya Atmospheric and Oceanic Physics (IzAOP)" },
    { value: "EGSGA", label: "E&amp;G Quaternary Science Journal (EGSGA)" },
    { value: "ComAp", label: "Comments on Astrophysics (ComAp)" },
    { value: "ChEG", label: "Chemie der Erde / Geochemistry (ChEG)" },
    { value: "JLasA", label: "Journal of Laser Applications (JLasA)" },
    { value: "IJGMM", label: "International Journal of Geometric Methods in Modern Physics (IJGMM)" },
    { value: "MMI", label: "Metals and Materials International (MMI)" },
    { value: "IzKry", label: "Izvestiya Ordena Trudovogo Krasnogo Znameni Krymskoj Astrofizicheskoj Observatorii (IzKry)" },
    { value: "EaInt", label: "Earth Interactions (EaInt)" },
    { value: "Freq", label: "Frequenz (Freq)" },
    { value: "LicOB", label: "Lick Observatory Bulletin (LicOB)" },
    { value: "IJSTA", label: "IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing (IJSTA)" },
    { value: "PCEA", label: "Physics and Chemistry of the Earth A (PCEA)" },
    { value: "CoSka", label: "Contributions of the Astronomical Observatory Skalnate Pleso (CoSka)" },
    { value: "BiBi", label: "Bioinspiration and Biomimetics (BiBi)" },
    { value: "AeoRe", label: "Aeolian Research (AeoRe)" },
    { value: "AdAst", label: "Advances in Astronomy (AdAst)" },
    { value: "DeHyZ", label: "Deutsche Hydrographische Zeitschrift (DeHyZ)" },
    { value: "SvJPP", label: "Soviet Journal of Plasma Physics (SvJPP)" },
    { value: "IEITI", label: "IEICE Transactions on Information and Systems (IEITI)" },
    { value: "FrPhy", label: "Frontiers of Physics (FrPhy)" },
    { value: "EAS", label: "EAS Publications Series (EAS)" },
    { value: "Physi", label: "Physics (Physi)" },
    { value: "ITAC", label: "IEEE Transactions on Automatic Control (ITAC)" },
    { value: "AnHar", label: "Annals of Harvard College Observatory (AnHar)" },
    { value: "RCD", label: "Regular and Chaotic Dynamics (RCD)" },
    { value: "GescJ", label: "Geosciences Journal (GescJ)" },
    { value: "JMPh", label: "Journal of Modern Physics (JMPh)" },
    { value: "AuJPA", label: "Australian Journal of Physics Astrophysical Supplement (AuJPA)" },
    { value: "SSI", label: "Space Science Instrumentation (SSI)" },
    { value: "JPhys", label: "Journal de Physique (JPhys)" },
    { value: "SJADS", label: "SIAM Journal on Applied Dynamical Systems (SJADS)" },
    { value: "PhLRv", label: "Physics of Life Reviews (PhLRv)" },
    { value: "IJMPS", label: "International Journal of Modern Physics Conference Series (IJMPS)" },
    { value: "JGeEd", label: "Journal of Geoscience Education (JGeEd)" },
    { value: "JBR", label: "Journal of Breath Research (JBR)" },
    { value: "PhuZ", label: "Physik in unserer Zeit (PhuZ)" },
    { value: "EML", label: "Electronic Materials Letters (EML)" },
    { value: "KFNT", label: "Kinematika i Fizika Nebesnykh Tel (KFNT)" },
    { value: "ApL&C", label: "Astrophysical Letters and Communications (ApL&C)" },
    { value: "IJAsB", label: "International Journal of Astrobiology (IJAsB)" },
    { value: "HWM", label: "Helgol&auml;nder Wissenschaftliche Meeresuntersuchungen (HWM)" },
    { value: "AMTD", label: "Atmospheric Measurement Techniques Discussions (AMTD)" },
    { value: "JRadR", label: "Journal of Radiation Research (JRadR)" },
    { value: "HEAD", label: "AAS/High Energy Astrophysics Division (HEAD)" },
    { value: "HMR", label: "Helgoland Marine Research (HMR)" },
    { value: "ChJPh", label: "Chinese Journal of Physics (ChJPh)" },
    { value: "IJOE", label: "IEEE Journal of Oceanic Engineering (IJOE)" },
    { value: "JRP", label: "Journal of Radiological Protection (JRP)" },
    { value: "JOptT", label: "Journal of Optical Technology (JOptT)" },
    { value: "PZ", label: "Peremennye Zvezdy (PZ)" },
    { value: "CMMPh", label: "Computational Mathematics and Mathematical Physics (CMMPh)" },
    { value: "MCM", label: "Mechanics of Composite Materials (MCM)" },
    { value: "PPNL", label: "Physics of Particles and Nuclei Letters (PPNL)" },
    { value: "IrAJ", label: "Irish Astronomical Journal (IrAJ)" },
    { value: "ARAC", label: "Annual Review of Analytical Chemistry (ARAC)" },
    { value: "IJCFD", label: "International Journal of Computational Fluid Dynamics (IJCFD)" },
    { value: "AcSSn", label: "Acta Seismologica Sinica (AcSSn)" },
    { value: "CoASP", label: "Comments on Astrophysics and Space Physics (CoASP)" },
    { value: "NewSc", label: "New Scientist (NewSc)" },
    { value: "IzSSR", label: "Akademiia Nauk SSSR Izvestiia Seriia Fizicheskaia (IzSSR)" },
    { value: "NuAlg", label: "Numerical Algorithms (NuAlg)" },
    { value: "ResPh", label: "Results in Physics (ResPh)" },
    { value: "JIMO", label: "WGN, Journal of the International Meteor Organization (JIMO)" },
    { value: "FNCN", label: "Fullerene Nanotubes and Carbon Nanostructures (FNCN)" },
    { value: "JO", label: "Journal des Observateurs (JO)" },
    { value: "CzJPS", label: "Czechoslovak Journal of Physics Supplement (CzJPS)" },
    { value: "JGE", label: "Journal of Geophysics and Engineering (JGE)" },
    { value: "JIEEJ", label: "Journal of The Institute of Electrical Engineers of Japan (JIEEJ)" },
    { value: "SolE", label: "Solid Earth (SolE)" },
    { value: "IJDE", label: "International Journal of Digital Earth (IJDE)" },
    { value: "JIPM", label: "Journal of Information Processing and Management (JIPM)" },
    { value: "BAAA", label: "Boletin de la Asociacion Argentina de Astronomia La Plata Argentina (BAAA)" },
    { value: "JHA", label: "Journal for the History of Astronomy (JHA)" },
    { value: "QuOpt", label: "Quantum Optics (QuOpt)" },
    { value: "CoLPL", label: "Communications of the Lunar and Planetary Laboratory (CoLPL)" },
    { value: "IzPSE", label: "Izvestiya Physics of the Solid Earth (IzPSE)" },
    { value: "cosp", label: "COSPAR Scientific Assembly (cosp)" },
    { value: "OMExp", label: "Optical Materials Express (OMExp)" },
    { value: "AstBu", label: "Astrophysical Bulletin (AstBu)" },
    { value: "SCoA", label: "Smithsonian Contributions to Astrophysics (SCoA)" },
    { value: "ITGE", label: "IEEE Transactions on Geoscience Electronics (ITGE)" },
    { value: "GeoSu", label: "Geophysical Surveys (GeoSu)" },
    { value: "RSTEd", label: "Research in Science and Technological Education (RSTEd)" },
    { value: "JSMEB", label: "JSME International Journal Series B (JSMEB)" },
    { value: "PCEB", label: "Physics and Chemistry of the Earth B (PCEB)" },
    { value: "ASIB", label: "NATO Advanced Science Institutes (ASI) Series B (ASIB)" },
    { value: "LPRv", label: "Laser & Photonics Review (LPRv)" },
    { value: "PhyEs", label: "Physics Essays (PhyEs)" },
    { value: "InEPS", label: "Indian Academy of Sciences Proceedings: Earth and Planetary Sciences (InEPS)" },
    { value: "ApPRv", label: "Applied Physics Reviews (ApPRv)" },
    { value: "JAnSc", label: "Journal of the Astronautical Sciences (JAnSc)" },
    { value: "OptEL", label: "Optoelectronics Letters (OptEL)" },
    { value: "MPBu", label: "Minor Planet Bulletin (MPBu)" },
    { value: "AnaCh", label: "Analytical Chemistry (AnaCh)" },
    { value: "CosEl", label: "Cosmic Electrodynamics (CosEl)" },
    { value: "RvMA", label: "Reviews in Modern Astronomy (RvMA)" },
  ];
});
