
        // GENERATED FILE (edits will be overwritten)
        module.exports = {
  "landing-page": {
    "options": {
      "waitSeconds": 0,
      "logLevel": 1,
      "baseUrl": "dist",
      "optimize": "none",
      "mainConfigFile": "dist/config/discovery.config.js",
      "deps": [],
      "findNestedDependencies": false,
      "create": true,
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "bowser": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "filesaver": "empty:",
        "google-recaptcha": "empty:",
        "google-analytics": "empty:",
        "jquery": "empty:",
        "jquery-ui": "empty:",
        "jquery-querybuilder": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:",
        "discovery.vars": "empty:",
        "yup": "empty:",
        "react-hook-form": "empty:",
        "react-flexview": "empty:",
        "styled-components": "empty:",
        "react-is": "empty:",
        "react-data-table-component": "empty:",
        "react-window": "empty:",
        "react-async": "empty:",
        "diff": "empty:",
        "hotkeys": "empty:",
        "react-transition-group": "empty:",
        "regenerator-runtime": "empty:",
        "@hookform/resolvers": "empty:"
      },
      "stubModules": [
        "es6",
        "babel"
      ],
      "name": "landing-page.bundle",
      "out": "dist/config/landing-page.bundle.js",
      "include": [
        "js/react/Recommender/actions",
        "js/react/Recommender/containers/main",
        "js/react/Recommender/index",
        "js/react/Recommender/middleware",
        "js/react/Recommender/models/index",
        "js/react/Recommender/models/searchExamples",
        "js/react/Recommender/reducer",
        "js/widgets/paper_search_form/topterms",
        "js/widgets/paper_search_form/widget",
        "js/widgets/search_bar/autocomplete",
        "js/widgets/search_bar/quick-field-desc",
        "js/widgets/search_bar/search_bar_widget",
        "js/widgets/facet/actions",
        "js/widgets/facet/create_store",
        "js/widgets/facet/factory",
        "js/widgets/facet/graph-facet/base_graph",
        "js/widgets/facet/graph-facet/h_index_graph",
        "js/widgets/facet/graph-facet/widget",
        "js/widgets/facet/graph-facet/year_graph",
        "js/widgets/facet/reducers",
        "js/widgets/facet/widget",
        "js/widgets/alerts/modal_view",
        "js/widgets/alerts/page_top_alert",
        "js/widgets/alerts/widget",
        "js/widgets/base/base_widget",
        "js/widgets/classic_form/widget",
        "js/widgets/footer/widget",
        "js/widgets/navbar/widget",
        "js/widgets/widget_states",
        "js/wraps/alerts_mediator",
        "js/wraps/discovery_mediator",
        "js/wraps/landing_page_manager/landing_page_manager"
      ]
    }
  },
  "search-page": {
    "options": {
      "waitSeconds": 0,
      "logLevel": 1,
      "baseUrl": "dist",
      "optimize": "none",
      "mainConfigFile": "dist/config/discovery.config.js",
      "deps": [],
      "findNestedDependencies": false,
      "create": true,
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "bowser": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "filesaver": "empty:",
        "google-recaptcha": "empty:",
        "google-analytics": "empty:",
        "jquery": "empty:",
        "jquery-ui": "empty:",
        "jquery-querybuilder": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:",
        "discovery.vars": "empty:",
        "yup": "empty:",
        "react-hook-form": "empty:",
        "react-flexview": "empty:",
        "styled-components": "empty:",
        "react-is": "empty:",
        "react-data-table-component": "empty:",
        "react-window": "empty:",
        "react-async": "empty:",
        "diff": "empty:",
        "hotkeys": "empty:",
        "react-transition-group": "empty:",
        "regenerator-runtime": "empty:",
        "@hookform/resolvers": "empty:"
      },
      "stubModules": [
        "es6",
        "babel"
      ],
      "name": "search-page.bundle",
      "out": "dist/config/search-page.bundle.js",
      "include": [
        "js/wraps/affiliation_facet",
        "js/wraps/author_facet",
        "js/wraps/bibgroup_facet",
        "js/wraps/bibstem_facet",
        "js/wraps/data_facet",
        "js/wraps/database_facet",
        "js/wraps/grants_facet",
        "js/wraps/keyword_facet",
        "js/wraps/ned_object_facet",
        "js/wraps/pubtype_facet",
        "js/wraps/refereed_facet",
        "js/wraps/simbad_object_facet",
        "js/wraps/vizier_facet",
        "js/widgets/metrics/d3-tip",
        "js/widgets/metrics/extractor_functions",
        "js/widgets/metrics/widget",
        "js/widgets/list_of_things/details_widget",
        "js/widgets/list_of_things/infinite_view",
        "js/widgets/list_of_things/item_view",
        "js/widgets/list_of_things/model",
        "js/widgets/list_of_things/paginated_view",
        "js/widgets/list_of_things/widget",
        "js/widgets/search_bar/autocomplete",
        "js/widgets/search_bar/quick-field-desc",
        "js/widgets/search_bar/search_bar_widget",
        "js/widgets/facet/actions",
        "js/widgets/facet/create_store",
        "js/widgets/facet/factory",
        "js/widgets/facet/graph-facet/base_graph",
        "js/widgets/facet/graph-facet/h_index_graph",
        "js/widgets/facet/graph-facet/widget",
        "js/widgets/facet/graph-facet/year_graph",
        "js/widgets/facet/reducers",
        "js/widgets/facet/widget",
        "js/widgets/alerts/modal_view",
        "js/widgets/alerts/page_top_alert",
        "js/widgets/alerts/widget",
        "js/widgets/abstract/widget",
        "js/widgets/api_query/widget",
        "js/widgets/base/base_widget",
        "js/widgets/bubble_chart/widget",
        "js/widgets/citation_helper/widget",
        "js/widgets/dropdown-menu/widget",
        "js/widgets/filter_visualizer/widget",
        "js/widgets/footer/widget",
        "js/widgets/navbar/widget",
        "js/widgets/network_vis/network_widget",
        "js/widgets/query_info/query_info_widget",
        "js/widgets/results/widget",
        "js/widgets/tabs/tabs_widget",
        "js/widgets/widget_states",
        "js/widgets/wordcloud/widget",
        "js/wraps/alerts_mediator",
        "js/wraps/discovery_mediator",
        "js/wraps/export_dropdown",
        "js/wraps/graph_tabs",
        "js/wraps/results_page_manager",
        "js/wraps/visualization_dropdown",
        "libs/select2/matcher"
      ]
    }
  },
  "abstract-page": {
    "options": {
      "waitSeconds": 0,
      "logLevel": 1,
      "baseUrl": "dist",
      "optimize": "none",
      "mainConfigFile": "dist/config/discovery.config.js",
      "deps": [],
      "findNestedDependencies": false,
      "create": true,
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "bowser": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "filesaver": "empty:",
        "google-recaptcha": "empty:",
        "google-analytics": "empty:",
        "jquery": "empty:",
        "jquery-ui": "empty:",
        "jquery-querybuilder": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:",
        "discovery.vars": "empty:",
        "yup": "empty:",
        "react-hook-form": "empty:",
        "react-flexview": "empty:",
        "styled-components": "empty:",
        "react-is": "empty:",
        "react-data-table-component": "empty:",
        "react-window": "empty:",
        "react-async": "empty:",
        "diff": "empty:",
        "hotkeys": "empty:",
        "react-transition-group": "empty:",
        "regenerator-runtime": "empty:",
        "@hookform/resolvers": "empty:"
      },
      "stubModules": [
        "es6",
        "babel"
      ],
      "name": "abstract-page.bundle",
      "out": "dist/config/abstract-page.bundle.js",
      "include": [
        "js/wraps/affiliation_facet",
        "js/wraps/author_facet",
        "js/wraps/bibgroup_facet",
        "js/wraps/bibstem_facet",
        "js/wraps/data_facet",
        "js/wraps/database_facet",
        "js/wraps/grants_facet",
        "js/wraps/keyword_facet",
        "js/wraps/ned_object_facet",
        "js/wraps/pubtype_facet",
        "js/wraps/refereed_facet",
        "js/wraps/simbad_object_facet",
        "js/wraps/vizier_facet",
        "js/widgets/metrics/d3-tip",
        "js/widgets/metrics/extractor_functions",
        "js/widgets/metrics/widget",
        "js/widgets/list_of_things/details_widget",
        "js/widgets/list_of_things/infinite_view",
        "js/widgets/list_of_things/item_view",
        "js/widgets/list_of_things/model",
        "js/widgets/list_of_things/paginated_view",
        "js/widgets/list_of_things/widget",
        "js/widgets/search_bar/autocomplete",
        "js/widgets/search_bar/quick-field-desc",
        "js/widgets/search_bar/search_bar_widget",
        "js/widgets/facet/actions",
        "js/widgets/facet/create_store",
        "js/widgets/facet/factory",
        "js/widgets/facet/graph-facet/base_graph",
        "js/widgets/facet/graph-facet/h_index_graph",
        "js/widgets/facet/graph-facet/widget",
        "js/widgets/facet/graph-facet/year_graph",
        "js/widgets/facet/reducers",
        "js/widgets/facet/widget",
        "js/widgets/alerts/modal_view",
        "js/widgets/alerts/page_top_alert",
        "js/widgets/alerts/widget",
        "js/widgets/abstract/widget",
        "js/widgets/base/base_widget",
        "js/widgets/footer/widget",
        "js/widgets/graphics/widget",
        "js/widgets/meta_tags/widget",
        "js/widgets/navbar/widget",
        "js/widgets/query_info/query_info_widget",
        "js/widgets/widget_states",
        "js/wraps/abstract_page_library_add/widget",
        "js/wraps/abstract_page_manager/abstract_page_manager",
        "js/wraps/alerts_mediator",
        "js/wraps/citations",
        "js/wraps/coreads",
        "js/wraps/discovery_mediator",
        "js/wraps/paper_export",
        "js/wraps/paper_metrics",
        "js/wraps/references",
        "js/wraps/sidebar-graphics-widget",
        "js/wraps/table_of_contents",
        "libs/select2/matcher"
      ]
    }
  },
  "main": {
    "options": {
      "waitSeconds": 0,
      "logLevel": 1,
      "baseUrl": "dist",
      "optimize": "none",
      "mainConfigFile": "dist/config/discovery.config.js",
      "deps": [],
      "findNestedDependencies": false,
      "create": true,
      "paths": {
        "backbone-validation": "empty:",
        "backbone.stickit": "empty:",
        "backbone.wreqr": "empty:",
        "backbone": "empty:",
        "bootstrap": "empty:",
        "bowser": "empty:",
        "classnames": "empty:",
        "clipboard": "empty:",
        "create-react-class": "empty:",
        "d3-cloud": "empty:",
        "d3": "empty:",
        "filesaver": "empty:",
        "google-recaptcha": "empty:",
        "google-analytics": "empty:",
        "jquery": "empty:",
        "jquery-ui": "empty:",
        "jquery-querybuilder": "empty:",
        "jsonpath": "empty:",
        "marionette": "empty:",
        "mathjax": "empty:",
        "moment": "empty:",
        "persist-js": "empty:",
        "react-bootstrap": "empty:",
        "react-dom": "empty:",
        "prop-types": "empty:",
        "react-redux": "empty:",
        "react": "empty:",
        "redux-thunk": "empty:",
        "redux": "empty:",
        "requirejs": "empty:",
        "reselect": "empty:",
        "select2": "empty:",
        "sinon": "empty:",
        "sprintf": "empty:",
        "underscore": "empty:",
        "discovery.vars": "empty:",
        "yup": "empty:",
        "react-hook-form": "empty:",
        "react-flexview": "empty:",
        "styled-components": "empty:",
        "react-is": "empty:",
        "react-data-table-component": "empty:",
        "react-window": "empty:",
        "react-async": "empty:",
        "diff": "empty:",
        "hotkeys": "empty:",
        "react-transition-group": "empty:",
        "regenerator-runtime": "empty:",
        "@hookform/resolvers": "empty:"
      },
      "stubModules": [
        "es6",
        "babel"
      ],
      "name": "main.bundle",
      "out": "dist/config/main.bundle.js",
      "include": [
        "config/common.config",
        "config/discovery.config",
        "js/apps/discovery/main",
        "js/apps/discovery/navigator",
        "js/components/alerts",
        "js/components/alerts_mediator",
        "js/components/api_feedback",
        "js/components/api_query",
        "js/components/api_query_updater",
        "js/components/api_request",
        "js/components/api_request_queue",
        "js/components/api_response",
        "js/components/api_targets",
        "js/components/app_storage",
        "js/components/application",
        "js/components/beehive",
        "js/components/csrf_manager",
        "js/components/default_request",
        "js/components/doc_stash_controller",
        "js/components/experiments",
        "js/components/facade",
        "js/components/feedback_mediator",
        "js/components/generic_module",
        "js/components/history_manager",
        "js/components/hotkeys_controller",
        "js/components/json_response",
        "js/components/library_controller",
        "js/components/multi_params",
        "js/components/navigator",
        "js/components/paginator",
        "js/components/persistent_storage",
        "js/components/pubsub_events",
        "js/components/pubsub_key",
        "js/components/query_mediator",
        "js/components/query_validator",
        "js/components/recaptcha_manager",
        "js/components/second_order_controller",
        "js/components/services_container",
        "js/components/session",
        "js/components/solr_params",
        "js/components/solr_response",
        "js/components/transition",
        "js/components/transition_catalog",
        "js/components/user",
        "js/mixins/add_secondary_sort",
        "js/mixins/add_stable_index_to_collection",
        "js/mixins/api_access",
        "js/mixins/dependon",
        "js/mixins/discovery_bootstrap",
        "js/mixins/expose_metadata",
        "js/mixins/form_view_functions",
        "js/mixins/formatter",
        "js/mixins/hardened",
        "js/mixins/link_generator_mixin",
        "js/mixins/openurl_generator",
        "js/mixins/papers_utils",
        "js/mixins/side_bar_manager",
        "js/mixins/user_change_rows",
        "js/mixins/widget_mixin_method",
        "js/mixins/widget_pagination",
        "js/mixins/widget_state_handling",
        "js/mixins/widget_state_manager",
        "js/mixins/widget_utility",
        "js/modules/hello",
        "js/modules/orcid/bio",
        "js/modules/orcid/extension",
        "js/modules/orcid/item_view_extension",
        "js/modules/orcid/module",
        "js/modules/orcid/orcid_api",
        "js/modules/orcid/profile",
        "js/modules/orcid/widget/widget",
        "js/modules/orcid/work",
        "js/page_managers/controller",
        "js/page_managers/master",
        "js/page_managers/one_column_view",
        "js/page_managers/three_column_view",
        "js/page_managers/toc_controller",
        "js/page_managers/toc_widget",
        "js/page_managers/view_mixin",
        "js/services/api",
        "js/services/default_pubsub",
        "js/services/pubsub",
        "js/services/storage",
        "analytics",
        "router",
        "utils",
        "recaptcha",
        "reactify",
        "js/bugutils/diagnostics",
        "js/react/BumblebeeWidget",
        "cache",
        "hbs",
        "async",
        "hbs/handlebars",
        "hbs/json2",
        "hbs/underscore",
        "array-flat-polyfill",
        "regenerator-runtime",
        "hotkeys",
        "react-transition-group",
        "@hookform/resolvers"
      ]
    }
  }
};
      