name: Node.js CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '11.14.0'
        architecture: 'x64'
    - run: npm install -g grunt-cli
    - run: npm ci
    - run: grunt setup
    - run: grunt test:prod

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: "test/coverage/reports/lcov/lcov.info"

